export const displayOptions = [
  { value: "flex", label: "flex" },
  { value: "", label: "Default" },
  { value: "block", label: "block" },
  { value: "inline", label: "inline" },
  { value: "inline-block", label: "inline-block" },
  { value: "inline-flex", label: "inline-flex" },
  { value: "inline-grid", label: "inline-grid" },
  { value: "grid", label: "grid" },
  { value: "inherit", label: "inherit" },
  { value: "initial", label: "initial" },
  { value: "none", label: "none" },
  { value: "run-in", label: "run-in" },
  { value: "table", label: "table" },
  { value: "table-caption", label: "table-caption" },
  { value: "table-column-group", label: "table-column-group" },
  { value: "table-header-group", label: "table-header-group" },
  { value: "table-footer-group", label: "table-footer-group" },
  { value: "table-row-group", label: "table-row-group" },
  { value: "table-cell", label: "table-cell" },
  { value: "table-column", label: "table-column" },
  { value: "table-row", label: "table-row" },
  { value: "list-item", label: "list-item" },
];
